name: Convert lilypond files

on:
  push:

env:
  LILYPOND_VERSION: 2.18.2

jobs:
  create-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download shell script
      run: wget https://lilypond.org/downloads/binaries/linux-64/lilypond-2.18.2-1.linux-64.sh

    - name: Make shell script executable
      run: chmod +x lilypond-2.18.2-1.linux-64.sh

    - name: Call shell script
      run: ./lilypond-2.18.2-1.linux-64.sh

    - name: Test version
      run: /home/runner/bin/lilypond --version

    # - name: Create folder for converted songs
    #   run:

    - name: Create files
      run: |
        mkdir converted_songs
        cd songs
        for file in *; do
          if [ -f "$file" ]; then
            base_filename=`basename "${file%.*}"`
            directory_name="../converted_songs/${base_filename}"
            mkdir "${directory_name}"
            /home/runner/bin/lilypond -dbackend=svg -o "$directory_name" "$file"
          fi
        done

    - name: Save artifacts
      uses: actions/upload-artifact@v2
      with:
        name: converted_songs
        path: converted_songs
