name: Convert lilypond files

on:
  push:

env:
  LILYPOND_VERSION: 2.18.2

jobs:
  create-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget -Olilypond.deb https://download.linuxaudio.org/lilypond/binaries/linux-64/lilypond-${LILYPOND_VERSION}-1.linux-64.deb
        sudo dpkg -i lilypond.deb

    - name: Create files
      run: |
        lilypond -dbackend=svg songs/varRedo.ly

    - name: Create svgs folder
      run: |
        mkdir converted_songs
        mv varRedo.midi varRedo-1.midi varRedo-2.midi varRedo-3.midi varRedo-4.midi varRedo.svg converted_songs/

    - name: Save artifacts
      uses: actions/upload-artifact@v2
      with:
        name: converted_songs
        path: converted_songs
