name: Convert lilypond files

on:
  push:

env:
  LILYPOND_VERSION: 2.18.2

jobs:
  create-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download LilyPond 2.24.0 archive
      run: wget https://gitlab.com/lilypond/lilypond/-/releases/v2.24.0/downloads/lilypond-2.24.0-linux-x86_64.tar.gz

    - name: Install LilyPond 2.24.0
      run: tar -xzvf lilypond-2.24.0-linux-x86_64.tar.gz

    - name: make converted_songs directory
      run: mkdir converted_songs

    - name: ls
      run: ls

    - name: Convert files (lilypond 2.24.0)
      run: |
        ./convert-songs-2.24.0.sh
    - name: Save artifacts
      uses: actions/upload-artifact@v2
      with:
        name: converted_songs
        path: converted_songs
        
    # - name: Download shell script
    #   run: wget https://lilypond.org/downloads/binaries/linux-64/lilypond-2.18.2-1.linux-64.sh

    # - name: Make shell script executable
    #   run: chmod +x lilypond-2.18.2-1.linux-64.sh

    # - name: Call shell script
    #   run: ./lilypond-2.18.2-1.linux-64.sh

    # - name: Convert files (lilypond 2.18.2)
    #   run: |
    #     ./convert-songs-2_18_2.sh

    # - name: Save artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: converted_songs
    #     path: converted_songs
