name: Convert lilypond files

on:
  push:

env:
  LILYPOND_VERSION: 2.18.2

jobs:
  create-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download lilypond
      run: wget https://lilypond.org/downloads/binaries/linux-64/lilypond-2.18.2-1.linux-64.sh

    - name: Make lilypond executable
      run: chmod +x lilypond-2.18.2-1.linux-64.sh

    - name: Install lilypond
      run: ./lilypond-2.18.2-1.linux-64.sh --batch

    - name: Add lilypond to PATH
      run: echo 'export PATH="$PATH:/usr/local/bin"' >> $GITHUB_ENV

    - name: Verify installation
      run: |
        lilypond --version


    - name: Create files
      run: |
        lilypond -dbackend=svg songs/varRedo.ly

    - name: Create svgs folder
      run: |
        mkdir converted_songs
        mv varRedo.midi varRedo-1.midi varRedo-2.midi varRedo-3.midi varRedo-4.midi varRedo.svg converted_songs/

    - name: Save artifacts
      uses: actions/upload-artifact@v2
      with:
        name: converted_songs
        path: converted_songs
