name: Create files

on:
  push:

jobs:
  create-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create files
      run: |
        echo "file1 content" > svgs/file1.txt
        echo "file2 content" > svgs/file2.txt
        echo "file3 content" > svgs/file3.txt
